receivers:
  otlp:
    endpoint: 0.0.0.0:9100
  zipkin:
    endpoint: 0.0.0.0:9411
exporters:
  logging:
    loglevel: info
  awsxray:
    local_mode: true
service:
  pipelines:
    traces:
      receivers:
      - otlp
      - zipkin
      exporters:
      - logging
      - awsxray
